delete_merged_branches = true

status = [
  ### GPU CI (Buildkite):
  "buildkite/kernelabstractions-dot-jl/julia-1-dot-5",
  "buildkite/kernelabstractions-dot-jl/julia-1-dot-6-nightly",
  # "buildkite/kernelabstractions-dot-jl/julia-nightly",

  ### CPU CI (GitHub Actions):
  "CI (1, macOS-latest, x64)",
  "CI (1, ubuntu-latest, x64)",
  "CI (1, windows-latest, x64)",
  "CI (1.3, macOS-latest, x64)",
  "CI (1.3, ubuntu-latest, x64)",
  "CI (1.3, windows-latest, x64)",
  "CI (1.4, macOS-latest, x64)",
  "CI (1.4, ubuntu-latest, x64)",
  "CI (1.4, windows-latest, x64)",
  "CI (1.5, macOS-latest, x64)",
  "CI (1.5, ubuntu-latest, x64)",
  "CI (1.5, windows-latest, x64)",
  # "CI-julia-1-6-nightly (1.6-nightly, macOS-latest, x64)",
  # "CI-julia-1-6-nightly (1.6-nightly, ubuntu-latest, x64)",
  # "CI-julia-1-6-nightly (1.6-nightly, windows-latest, x64)",
  "CI-julia-nightly (nightly, macOS-latest, x64)",
  "CI-julia-nightly (nightly, ubuntu-latest, x64)",
  "CI-julia-nightly (nightly, windows-latest, x64)",
  "Doctests",
  "Documentation",
]

timeout_sec = 3600
