name = "KernelAbstractions"
uuid = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
authors = ["Valentin Churavy <v.churavy@gmail.com> and contributors"]
version = "0.9.13"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
UnsafeAtomics = "013be700-e6cd-48c3-b4a1-df204f14c38f"
UnsafeAtomicsLLVM = "d80eeb9a-aca5-4d75-85e5-170c8b632249"

[compat]
Adapt = "0.4, 1.0, 2.0, 3.0"
Atomix = "0.1"
EnzymeCore = "0.5, 0.6"
MacroTools = "0.5"
PrecompileTools = "1"
Requires = "1.3"
StaticArrays = "0.12, 1.0"
UnsafeAtomics = "0.2.1"
UnsafeAtomicsLLVM = "0.1"
InteractiveUtils = "1.6"
LinearAlgebra = "1.6"
SparseArrays = "<0.0.1, 1.6"
UUIDs = "<0.0.1, 1.6"
julia = "1.6"

[extensions]
EnzymeExt = "EnzymeCore"

[extras]
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"

[weakdeps]
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
