name = "KernelAbstractions"
uuid = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.2.5"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDAapi = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Adapt = "0.4, 1.0"
CUDAapi = "3.0, 3.1, 4.0"
CUDAdrv = "6.1, 6.2"
CUDAnative = "3.0"
Cassette = "0.3.2"
MacroTools = "0.5"
SpecialFunctions = "0.10"
StaticArrays = "0.12"
julia = "1.3"
